config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"

  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: "task"
  get "tasks/:id/edit", to: "tasks#edit", as: "update"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: "delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to root_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |task| %>
<div class="form-group">
  <%= task.label :title %>
  <%= task.text_field :title, class: 'form-control'%>
</div>
<div class="form-group">
  <%= task.label :details %>
  <%= task.text_field :details, class: 'form-control' %>
</div>
<%= task.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/destroy.html.erb
<%= link_to "Delete", task_path(task),
  method: :delete,
  data: { confirm: "Are you sure?" } %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <h2> <%= link_to task.title, task_path(task) %> </h2>
  <input type="checkbox" value= <%= "task.completed" %> >
  <p> <%= link_to 'Destroy this task', delete_path(task), method: :delete %> </p>
<% end %>

<h4><%= link_to "Add a task", tasks_new_path %></h4>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<h4><%= @task.details %></h4>

<p> <%= link_to "Update this task", update_path %> </p>
<p> <%= link_to "Back to list", tasks_path %> </p>